config/routes.rb
Rails.application.routes.draw do
  
  resources :subjects  do 

    member do 
      get :delete 
    end

    collection do 
      get :index
    end

  end

 
  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'

  root 'demo#index'

  # get ':controller(/:action(:id))'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
    has_and_belongs_to_many :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
    belongs_to :subject, {:optional => false}
    has_many :sections
    has_and_belongs_to_many :admin_users 
end

app/models/section.rb
class Section < ApplicationRecord
    belongs_to :page
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :pages

    scope :visible, lambda {where(:visible => true)}
    scope :invisible, lambda {where(:visible => false)}
    scope :sorted, lambda {order(:position => :asc)}
    scope :newest_first, lambda {order(:created_at => :desc)}
    scope :search, lambda {|query| where(["name LIKE?", "%#{query}%"])}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false 

  def index
    render('index')
    
  end
  
  def hello 
    @page = params[:page]
    @id = params['id']
    render('hello')
  end

  def other_hello 
    redirect_to(:action => "hello")
  end

  def google 
    redirect_to('http://www.google.com')
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new 
  end
  
  def create 
    @subject = Subject.new(subject_params)
    if @subject.save 
      flash[:notice] = "Subject was created successfully"
      redirect_to subjects_path 
    else 
      render('new')
    end
  end


  def edit
    @subject = Subject.find(params[:id])
  end

  def update 
    @subject = Subject.find(params[:id])
    @subject = Subject.new(subject_params)
    if @subject.update_attributes(subject_params)
      flash[:notice] = "Subject #{@subject.name } was updated successfully"
      redirect_to(subject_path(@subject))
    else
      render('new')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
    
  end

  def destroy 
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject #{@subject.name} was destroyed successfully" 
    redirect_to(subjects_path)
  end


  private 

  def subject_params 
    params.require(:subject).permit(:name, :position, :visible)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/demo/hello.html.erb
<h1>hola mundo, desde hello.html</h1>

<%= link_to("ir a index", demo_index_path) %>

<br /> 

ID: <%= @id %><br /> 
ID: <%= params[:id] %><br/> 
page: <%= @page %><br/> 

next page: <%= @page.to_i + 1 %> 

app/views/demo/index.html.erb
<h1> hola mundo, desde vista index.html.erb </h1>

<%= 1+1 %><br />

<% target = "world" %> 

<%= "Hello #{target}" %> 
<br /> 

<% 3.times do |n| %> 
    <%= n %><br /> 
<% end %> 

<%= link_to("ir a hello", demo_hello_path) %><br />
<%= link_to("ir a google", {:controller => 'demo', :action => "google"} ) %> <br /> 

<%= link_to("hello with parameters", {:action => "hello", :page => 5, :id => 20}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subjects/delete.html.erb
<% if !flash[:notice].blank? %>
    <div class="notice"%> 
        <%= flash[:notice] %>
    </div>
<% end%> 
<%= link_to("volver", subjects_path)%>

<div class="subject delete" >
    <h2> Delete subject </h2>

    <%= form_for(@subject, :method => 'delete') do |f| %> 

    <p> ¿are you sure you want to permanently delete this subject?</p>

    <p class='reference-name'> <%= f.object.name %> </p>

    <div class="form-buttons"> 
        <%= f.submit("Delete subject") %>
    </div>

    <%end%>
</div> 

app/views/subjects/edit.html.erb
<% if !flash[:notice].blank? %>
    <div class="notice"%> 
        <%= flash[:notice] %>
    </div>
<% end%> 

<%= link_to("Volver a la lista", subjects_path, :class => "back-link") %>

<div class="subject news"> 
    <h2> Create subject </h2>

    <%= form_for @subject do |f| %>

    <table summary="subject form fields" > 
        <tr> 
            <th>name </th> 
            <td><%= f.text_field :name %>  </td>

        </tr>
        <tr> 
            <th>Position</th>
             <td><%= f.text_field :position %></td>
        </tr>
        <tr>
            <th>Visible</th>
            <td><%= f.text_field :visible %> </td>
        </tr>

    </table>

    <div class="form buttons">
        <%= f.submit "crear subject" %> 

    </div>

    
    
    
</div>
   
<% end %>

app/views/subjects/index.html.erb
<% if !flash[:notice].blank? %>
    <div class="notice"%> 
        <%= flash[:notice] %>
    </div>
<% end%> 

<div class="subjects index"> 
    <h2> Subjects </h2>

    <%= link_to("add new subject", new_subject_path, :class => "action new") %> 

    <table class ="listing" summary="subject list" > 
        <tr class="header" > 
            <th> #</th>
            <th> subject</th> 
            <th> visible </th>
            <th> pages </th>
            <th>actions </th> 
        </tr>
        <% @subjects.each do |subject| %> 
        <tr> 
            <td><%= subject.position %> </td>
            <td><%= subject.name %>  </td>
            <td class="center"> <%= subject.visible ? 'yes' : 'no' %> </td>
            <td class="center"> <%= subject.pages.size %> </td>
            <td class="actions"> 
                <%= link_to("show", subject_path(subject), :class => "action show") %>
                <%= link_to("edit", edit_subject_path(subject), :class => "action edit") %> 
                <%= link_to "delete", delete_subject_path(subject) %> 
                

            </td>
        </tr>
        <%end%> 

app/views/subjects/new.html.erb
<%= link_to("Volver a la lista", subjects_path, :class => "back-link") %>

<div class="subject news"> 
    <h2> Create subject </h2>

    <%= form_for @subject do |f| %>

    <table summary="subject form fields" > 
        <tr> 
            <th>name </th> 
            <td><%= f.text_field :name %>  </td>

        </tr>
        <tr> 
            <th>Position</th>
             <td><%= f.text_field :position %></td>
        </tr>
        <tr>
            <th>Visible</th>
            <td><%= f.text_field :visible %> </td>
        </tr>

    </table>

    <div class="form buttons">
        <%= f.submit "crear subject" %> 

    </div>

    
    
    
</div>
   
<% end %>

app/views/subjects/show.html.erb
<table summary="Subject detail" %> 
    <tr> 
        <th> name </th>
        <td> <%= @subject.name %> </td>
    </tr>
    <tr> 
        <th> position </th>
        <td> <%= @subject.position %> </td> 
    </tr>
    <tr> 
        <th> Visible? </th>
        <td> <%= @subject.visible ? 'true' : 'false' %> </td>
    </tr>
    <tr> 
        <th> created </th>
        <td> <%= @subject.created_at %> </td>
    </tr>
    <tr>
        <th> updated </th> 
        <td> <%= @subject.updated_at %> </td>
    </tr>
</table>

<%= link_to("volver", subjects_path) %>